# -*- coding: utf-8 -*-
"""22201698_Khan Farhan Mahdi_CSE440_01_Lab_Assignment01_Spring2026

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oZAL4uaTklhJ2Q6XD4QjdtIMbaEUGJMH

# **Initialization**
"""

import nltk

nltk.download("all")

from wordcloud import WordCloud
from nltk.probability import FreqDist
import matplotlib.pyplot as plt
from nltk.corpus import *
from tabulate import tabulate
import string
from nltk.util import ngrams
import numpy as np

"""# **Question-1**"""

from nltk.corpus import inaugural

inaugural.fileids()

from nltk.corpus import movie_reviews

movie_reviews.fileids()

"""# **Question-2**"""

from nltk.corpus import state_union

state_union.fileids()

truman=state_union.raw('1945-Truman.txt')
print(truman)

eisenhower=state_union.raw('1953-Eisenhower.txt')
print(eisenhower)

from nltk.tokenize import *

word1=word_tokenize(truman)
print(word1)

word2=word_tokenize(eisenhower)
print(word2)

fd1 = FreqDist(word1)
unique_words = list(set(word1))
wc = WordCloud(width = 800, height = 400, background_color= 'white')
cloud = wc.generate_from_frequencies(fd1)
plt.figure(figsize = (10,6))
plt.imshow(cloud)
plt.axis('on')

mostFreq1=fd1.max()
print(f"The most frequent word in truman is '{mostFreq1}'.")

fd2 = FreqDist(word2)
unique_words = list(set(word2))
wc = WordCloud(width = 800, height = 400, background_color= 'white')
cloud = wc.generate_from_frequencies(fd2)
plt.figure(figsize = (10,6))
plt.imshow(cloud)
plt.axis('on')

mostFreq2=fd2.max()
print(f"The most frequent word in eisenhower is '{mostFreq2}'.")

"""# **Question-3**"""

from nltk.corpus import stopwords
from nltk.stem import LancasterStemmer, PorterStemmer, SnowballStemmer
from nltk.stem import WordNetLemmatizer

movie_reviews.fileids("pos")

review=movie_reviews.raw('pos/cv955_25001.txt')
print(review)

words=word_tokenize(review)
lemmatizer=WordNetLemmatizer()

print(words)

stopWords=stopwords.words("english")
print(stopWords)

flitered_review=[lemmatizer.lemmatize(w.lower()) for w in words if w.lower() not in stopWords]
print(flitered_review)

wordCount= FreqDist(flitered_review)
mostFreq20=wordCount.most_common(20)
x=[i[0] for i in mostFreq20]
y=[i[1] for i in mostFreq20]
plt.figure(figsize=(12, 25))
plt.bar(x,y)
plt.title("Most Frequent 20 words")
plt.xlabel("Words")
plt.ylabel("Count")

"""# **Question-4**"""

lincoln=inaugural.raw('1861-Lincoln.txt')
tokens=word_tokenize(lincoln)

punctuations=string.punctuation
print(punctuations)

filtered_speech=[i.lower() for i in tokens if i.lower() not in stopWords and i not in punctuations]

print(filtered_speech)

wordCount=FreqDist(filtered_speech)
wordCount15=wordCount.most_common(15)
print(wordCount15)

top15=[i[0] for i in wordCount15]
print(top15)

bigrams=list(ngrams(top15, n = 2))
bigrams

unique_words=list(set(bigrams))
matrix=np.zeros((len(unique_words),len(unique_words)),dtype=int)
print(matrix)

wordIndex={}
for i,word in enumerate(unique_words):
  wordIndex[word]=i
print(wordIndex)

for i in range(len(filtered_speech)-1):
  current_word = filtered_speech[i]
  next_word = filtered_speech[i+1]
  if current_word in wordIndex and next_word in wordIndex:
        cw_index = wordIndex[current_word]
        nw_index = wordIndex[next_word]
        matrix[cw_index, nw_index] += 1

print("The Co-occurance matrix for the top 15 words:\n")
print(matrix)

"""# **Question-5**"""

from nltk.corpus import udhr

udhr.fileids()

german=udhr.raw('German_Deutsch-Latin1')
print(german)

words=word_tokenize(german)
print(words)

vowels="aeiouAEIOUäöüÄÖÜ"

filter=[]
for i in (words):
  vowel=""
  for y in i:
    if y in vowels and y!="":
      vowel+=y
  if vowel !="":
    filter.append(vowel)
print(filter)

trigrams=list(ngrams(filter,n=3))
print(trigrams)

freqCount=FreqDist(trigrams).most_common()
print(freqCount)